;;; evil-cursor-between-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-cursor-between-mode.el

(register-definition-prefixes "evil-cursor-between-mode" '("ad-evil-ex-search-adjust-offset" "evil-"))

;;; End of scraped data

(provide 'evil-cursor-between-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-cursor-between-mode-autoloads.el ends here
